### ISSUE TITLE
Sikulix Java Intellij setup

### ISSUE THREAD

**Issue by rstormsf** [RaiMan/SikuliX-2014#110]
when I cloned this repo https://github.com/RaiMan/MySikuliExample
and opened in NetBeans 8.0.2 on Mac - it works perfectly fine
I'm trying to run in Intellij IDEA Community Edition and it gives me errors:
```
[error] ResourceLoader: check: Terminating: The jar was not built with setup nor can the libs be exported from classpath!
/Users/storm/.m2/repository/com/sikulix/sikulixapi/1.1.0-SNAPSHOT/sikulixapi-1.1.0-20150116.001551-75.jar
```
all module settings setup for Compile

I have no idea why it is failing as soon as I call 
```
 Screen screen = new Screen();
```
Any help?

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at my.sikuli.example.MySikuliTest.main(MySikuliTest.java:24)
Caused by: java.lang.NullPointerException
	at org.sikuli.script.Screen.getPrimaryScreen(Screen.java:321)
	at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:199)
	at org.sikuli.script.Sikulix.terminate(Sikulix.java:180)
	at org.sikuli.basics.ResourceLoader.check(ResourceLoader.java:274)
	at org.sikuli.basics.FileManager.loadLibrary(FileManager.java:82)
	at org.sikuli.script.Screen.<clinit>(Screen.java:56)
```

is there any Global environments need to be setup?

**Comment by RaiMan** [comment]
Sorry, but you have to wait for the next nightly that will also bring the actual snapshot to OSSRH, which has a completely revised startup and library handling, hoping, that this will also work in other IDE's than NetBeans (what I am using for development).

**Comment by jordiponsllaurado** [comment]
I have the same problem. Is it already solved or still planned for the next nightly?

**Comment by RaiMan** [comment]
not solved yet. I am still busy with next nightly. sorry.

**Comment by RaiMan** [comment]
no activity
