### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it

### ISSUE THREAD

**Issue by Zoe1808** [RaiMan/SikuliX-2014#111]
When I run the scipt in Linux(ubuntu), i got an error like this.
How can i solve it?

Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.java2d.HeadlessGraphicsEnvironment.getScreenDevices(HeadlessGraphicsEnvironment.java:72)
	at org.sikuli.script.Screen.initScreens(Screen.java:72)
	at org.sikuli.script.Screen.<clinit>(Screen.java:59)
	... 45 more

**Comment by RaiMan** [comment]
SikuliX does not work on headless systems
