### ISSUE TITLE
Ubuntu 14.04 setup issue

### ISSUE THREAD

**Issue by nowickjo** [RaiMan/SikuliX-2014#121]
Any help would be appreciated.  I run the setup jar and select option 2 from the dialog. It downloads sikulixlibxlux.jar but then I get this error...

PS I have installed IDE in another folder and it works.

RunSetup: Copied from Downloads: sikulixlibslux
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.sikuli.util.LinuxSupport.buildVision(LinuxSupport.java:289)
	at org.sikuli.util.LinuxSupport.checkAllLibs(LinuxSupport.java:270)
	at org.sikuli.script.RunTime.loadLib(RunTime.java:1047)
	at org.sikuli.script.RunTime.loadLibrary(RunTime.java:1004)
	at org.sikuli.setup.RunSetup.main(RunSetup.java:642)

**Comment by RaiMan** [comment]
Yep, confirmed. Will fix it until tomorrow's nightly.

workaround:
add a valid 
JAVA_HOME=....
to environement.

**Comment by RaiMan** [comment]
no activity
