### ISSUE TITLE
UnicodeEncodeError on init with Windows username containing "ø".

### ISSUE THREAD

**Issue by chinatsu** [RaiMan/SikuliX-2014#131]
I'm opening this issue on behalf of a friend. I don't have the text copied directly, but I wrote off a screenshot([1]) for the sake of your convenience. Apparently the cmd-window closes too fast for him to copy it.

```
[error] RunTimeIDE:	*** terminating: JythonScriptRunner: cannot be initialized:

Traceback (most recent call last):
	File "D:\spam\sikuli\sikulix.jar\Lib\site.py", line 585, in <module>
	File "D:\spam\sikuli\sikulix.jar\Lib\site.py", line 567, in main
	File "D:\spam\sikuli\sikulix.jar\Lib\site.py", line 300, in addusersitepackages
	File "D:\spam\sikuli\sikulix.jar\Lib\site.py", line 289, in getusersitepackages
	File "D:\spam\sikuli\sikulix.jar\Lib\sysconfig.py", line 416, in get_path
	File "D:\spam\sikuli\sikulix.jar\Lib\sysconfig.py", line 407, in get_paths
	File "D:\spam\sikuli\sikulix.jar\Lib\sysconfig.py", line 180, in _expand_vars
	File "D:\spam\sikuli\sikulix.jar\Lib\sysconfig.py", line 154, in _subst_vars
	File "D:\spam\sikuli\sikulix.jar\Lib\sysconfig.py", line 154, in _subst_vars
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 10: ordinal not in range(128)
```

[1]: http://i.imgur.com/TosxXPh.png

**Comment by RaiMan** [comment]
I currently bundle Jython 2.7-rc3 with IDE 1.1.0, which apparently has some problems with unicode characters in different situations (especially with items in the system environment, which leads to that the interpreter cannot be started internally).
I will go back to version 2.5.4-rc1 (tomorrow's nightly build), since it does not look like these problems will be fixed in Jython the next days.

**Comment by techtonik** [comment]
I don't have time, expertise and environment for a test case to fill a bug report at http://bugs.jython.org/, but if somebody finds it, it will help to make next Jython 2.7 version Sikuli-compatible.

**Comment by RaiMan** [comment]
@techtonik 
this is already on the list there:
http://bugs.jython.org/issue2340

**Comment by tg44** [comment]
This is still a bug with usernames containing non ascii characters.

**Comment by vyau** [comment]
@tg44  I have had some success doing  u'my non-ascii text'
I am using the python interface and tried chinese characters.  If you "unicode" the string, it may work.

**Comment by tg44** [comment]
@vyau I tried to build the project from source (with Users/username/.m2/ dependencies) with a username which contains "ö". The IDE start is hanging on the Init scripts, and the jython's sysconfig.py l154 drops an asiic error. (I will use only jruby in the future, just mentioned this is still a bug.)
