### ISSUE TITLE
NPE when running VNC example

### ISSUE THREAD

**Issue by maliniakh** [RaiMan/SikuliX-2014#132]
I'm trying to run SikuliX with VNC. I started with StuffContainer/VNCMichaelJohnson/example.java and the problem I encountered is:

Exception in thread "main" java.lang.NullPointerException
	at org.sikuli.script.Mouse.click(Mouse.java:252)
	at org.sikuli.script.Region.click(Region.java:3256)
	at org.sikuli.script.Region.click(Region.java:3240)
	at edu.unh.iol.dlc.Example.main(Example.java:31)

It was caused just by calling: 

vnc.click(new Location(20, 20));

How come? Mouse.device field isn't initiated at the time of reaching Mouse.java:252. Surprisingly the example works when it's ran in debug mode. Is the 'device' field initiated in separate thread?

Any hints highly appreciated.

**Comment by RaiMan** [comment]
Sorry, overseen.

... but should be fixed now.

**Comment by maliniakh** [comment]
well done, thanks for quick fix.
