### ISSUE TITLE
Terminating on FatalError (invalid, r/o temp dir)

### ISSUE THREAD

**Issue by techtonik** [RaiMan/SikuliX-2014#142]
All of a sudden SikuliX stopped to work on my system. It shows a Swing? dialog with the following message:
```
Terminating on FatalError: cannot access IDE lock for\nC:\Users\user\AppData\Local\Temp\Sikulix_273542776\sikuli-ide-isrunning
```

I cleaned up Temp, but the error still there. How to debug that further?

**Comment by RaiMan** [comment]
could you please try with the latest build

**Comment by techtonik** [comment]
Installed using sikulixsetup-1.1.0-20150612.230952-102-forsetup.jar
```
>java -jar sikulix.jar
java.lang.RuntimeException: Failed to create temp dir with prefix 'BridJExtractedLibraries' despite 20 attempts!
        at org.bridj.Platform.createTempDir(Platform.java:577)
        at org.bridj.Platform.<clinit>(Platform.java:174)
        at org.bridj.CRuntime.<clinit>(CRuntime.java:456)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.bridj.BridJ.getRuntimeByRuntimeClass(BridJ.java:247)
        at org.bridj.BridJ.getRuntime(BridJ.java:278)
        at org.bridj.BridJ.register(BridJ.java:301)
        at org.bridj.BridJ.register(BridJ.java:162)
        at org.sikuli.util.SysJNA$WinKernel32.<clinit>(SysJNA.java:19)
        at org.sikuli.script.RunTime.addToWindowsSystemPath(RunTime.java:959)
        at org.sikuli.script.RunTime.libsExport(RunTime.java:918)
        at org.sikuli.script.RunTime.init(RunTime.java:671)
        at org.sikuli.script.RunTime.get(RunTime.java:290)
        at org.sikuli.ide.SikuliIDE.run(SikuliIDE.java:177)
        at org.sikuli.ide.Sikulix.main(Sikulix.java:21)
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
        at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
        at org.bridj.Platform.<clinit>(Platform.java:179)
        at org.bridj.CRuntime.<clinit>(CRuntime.java:456)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        at org.bridj.BridJ.getRuntimeByRuntimeClass(BridJ.java:247)
        at org.bridj.BridJ.getRuntime(BridJ.java:278)
        at org.bridj.BridJ.register(BridJ.java:301)
        at org.bridj.BridJ.register(BridJ.java:162)
        at org.sikuli.util.SysJNA$WinKernel32.<clinit>(SysJNA.java:19)
        at org.sikuli.script.RunTime.addToWindowsSystemPath(RunTime.java:959)
        at org.sikuli.script.RunTime.libsExport(RunTime.java:918)
        at org.sikuli.script.RunTime.init(RunTime.java:671)
        at org.sikuli.script.RunTime.get(RunTime.java:290)
        at org.sikuli.ide.SikuliIDE.run(SikuliIDE.java:177)
        at org.sikuli.ide.Sikulix.main(Sikulix.java:21)
```

**Comment by techtonik** [comment]
It appears that something changed my Temp dir to r/o on Vista. =/
