### ISSUE TITLE
Sikuli is failing on clicking on save button

### ISSUE THREAD

**Issue by antoaravinth** [RaiMan/SikuliX-2014#148]
Thanks for such a nice project!

I'm using `sikuli-java.jar` to automate notepad. This is what I'm trying, write something into the notepad and then save it. However, the final save click is not happening. Here is the code for it:

```
import org.sikuli.basics.Debug;
import org.sikuli.basics.Settings;
import org.sikuli.script.App;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Region;
import org.sikuli.script.Screen;


public class Main {

    public static void main(String[] args) throws FindFailed, InterruptedException {

        Debug.setDebugLevel(3);
        System.out.println(Settings.getVersion());

        Screen s = new Screen();

        App a = new App("Notepad");
        a.open();
        a.focus();

        Region region = a.focusedWindow();
        Thread.sleep(3000);
        region.type("hello world");
        region.click("C:\\Users\\Anto\\IdeaProjects\\sikuli\\imgs\\file.png");
        region.type("s");
        Thread.sleep(1000);
        s.click("C:\\Users\\Anto\\IdeaProjects\\sikuli\\imgs\\save.png");
    }
}
```

Here is the console output:

```
"C:\Program Files (x86)\Java\jdk1.8.0_45\bin\java" -Didea.launcher.port=7563 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.4\bin" -Dfile.encoding=windows-1252 -classpath "C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\jfxswt.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\rt.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_45\jre\lib\ext\zipfs.jar;C:\Users\Anto\IdeaProjects\sikuli\out\production\sikuli;C:\Users\Anto\Downloads\sikuli-java.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.1.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain Main
Sikuli 1.0.1
[debug] Screen: initScreens: basic initialization (1 Screen(s) found)
[debug] *** monitor configuration (primary: 0) ***
[debug] Screen 0: S(0)[0,0 1366x768]
[debug] *** end monitor configuration ***
[debug] ResourceLoaderBasic: SikuliX Package Build: 1.0.1 12SEP2013135849
[debug] ResourceLoaderBasic: check: we are running on arch: x86
[debug] ResourceLoaderBasic: check: using Java at: C:/Program Files (x86)/Java/jdk1.8.0_45/jre/
[debug] ResourceLoaderBasic: check: Exists libs folder at location of jar? YES: C:/Users/Anto/Downloads/
[debug] ResourceLoaderBasic: checkLibsDir: C:/Users/Anto/Downloads/libs
[debug] ResourceLoaderBasic: loadLib: WinUtil
[debug] ResourceLoaderBasic: loadLib: Found: WinUtil
[debug] ResourceLoaderBasic: loadLib: Now loaded: WinUtil
[debug] ResourceLoaderBasic: checkLibsDir: Using libs at: C:\Users\Anto\Downloads\libs
[debug] ResourceLoaderBasic: check: Using this as OCR directory (tessdata) too
[debug] ResourceLoaderBasic: loadLib: Is already loaded: WinUtil
[log] App.open Notepad(4552)
[log] App.focus Notepad(4552) #0
[error] App.focus failed: Notepad(4552) not found
[log] TYPE "hello world"
[debug] Robot: doType: H ( 72 )
[debug] Robot: doType: E ( 69 )
[debug] Robot: doType: L ( 76 )
[debug] Robot: doType: L ( 76 )
[debug] Robot: doType: O ( 79 )
[debug] Robot: doType: Space ( 32 )
[debug] Robot: doType: W ( 87 )
[debug] Robot: doType: O ( 79 )
[debug] Robot: doType: R ( 82 )
[debug] Robot: doType: L ( 76 )
[debug] Robot: doType: D ( 68 )
[debug] waiting for C:\Users\Anto\IdeaProjects\sikuli\imgs\file.png to appear
[debug] Screen.capture: java.awt.Rectangle[x=0,y=0,width=1362,height=736]
[debug] RobotDesktop: captureScreen: on 0 using java.awt.Rectangle[x=0,y=0,width=1362,height=736]
[debug] ResourceLoaderBasic: loadLib: VisionProxy
[debug] ResourceLoaderBasic: loadLib: Found: VisionProxy
[debug] ResourceLoaderBasic: loadLib: Now loaded: VisionProxy
[debug] C:\Users\Anto\IdeaProjects\sikuli\imgs\file.png has appeared.
[log] CLICK on L(265,229)@S(0)[0,0 1366x768]
[log] TYPE "s"
[debug] Robot: doType: S ( 83 )
[debug] waiting for C:\Users\Anto\IdeaProjects\sikuli\imgs\save.png to appear
[debug] Screen.capture: java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] RobotDesktop: captureScreen: on 0 using java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] Screen.capture: java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] RobotDesktop: captureScreen: on 0 using java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] Screen.capture: java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] RobotDesktop: captureScreen: on 0 using java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] Screen.capture: java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] RobotDesktop: captureScreen: on 0 using java.awt.Rectangle[x=0,y=0,width=1366,height=768]
[debug] C:\Users\Anto\IdeaProjects\sikuli\imgs\save.png has not appeared.
Exception in thread "main" FindFailed: can not find C:\Users\Anto\IdeaProjects\sikuli\imgs\save.png on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at org.sikuli.script.Region.find(Region.java:1590)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:1991)
	at org.sikuli.script.Region.click(Region.java:2197)
	at org.sikuli.script.Region.click(Region.java:2181)
	at Main.main(Main.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1
```

Even though save button is visible, this code is not working. The interesting part is the same code in python sikuli ide works!

```
. . .
click( "C:\\Users\\Anto\\IdeaProjects\\sikuli\\imgs\\save.png")
. . .
```

the above code in python able to click, however in java fails (note they are the same imgaes!), its bit confusing though.

Thanks for the help.

**Comment by RaiMan** [comment]
--- note they are the same images!
... this means, you have copied the images file.png and save.png form the .sikuli testcase to C:\\Users\\Anto\\IdeaProjects\\sikuli\\imgs\\ ?

--- its bit confusing though.
yes;-)
the only possible reasons (since the file.png was found)
- the save button took more than 3 seconds to appear
- the save button seen on the screen does not match with a score of at least 0.7

--- could you run your script example in the IDE and add 
Debug.setDebugLevel(3)
as the first line and compare the output.

A hint:
If you already have a .sikuli, that contains the images, then you can use in your Java code:
ImagePath.add("<absolule path to your .sikuli")

and then simply
region.click("file.png");

When not running in the IDE, it is good practice, to have a images.sikuli somewhere, that you use to manage your images and then add it to the image path.

One more thing:
If you are still in the phase of "beginning with Sikuli" you should check out version 1.1.0 pre final (http://sikulix.com)

**Comment by antoaravinth** [comment]
@RaiMan Oh I made a small mistake, the save.png was the screenshot that took by me using snipping tool(default tool) in windows 8. 

After I changed the save.png to the one which the IDE created, it worked flawless! Thinking what can be the cause?

Can you give me in-depth of what resolution does IDE takes the screenshots? Looks that works always! 

----If you are still in the phase of "beginning with Sikuli" you should check out version 1.1.0 pre final 

Yes we are in the starting phase, what is the diff between these two? 1.0.1 is deprecated?

**Comment by RaiMan** [comment]
---  what resolution does IDE takes the screenshots
just the RGB pixels as they are sent to the screen.
look for some explanations here:
http://sikulix-2014.readthedocs.org/en/latest/basicinfo.html#sikulix-how-does-it-find-images-on-the-screen
come back with questions then. 

--- 1.0.1 is deprecated?
yes, in the sense, that there will not be any fixes or new features. It is simply frozen.
1.1.0 has many enhancements (not everything documented yet) and is much more robust in setup and usage.
Just have a look and decide.
