### ISSUE TITLE
encoding problems when editing with something other than SikuliX IDE

### ISSUE THREAD

**Issue by pganuza** [RaiMan/SikuliX-2014#152]
When editing sikuli files with editors like atom and using UTF-8, sikuli fails to execute the test with the following error:
```
+++ JAVA_HOME specified but not useable  C:\Program Files (x86)\Java\jre1.8.0_45\bin
+++ looking for Java in system path and then in standard places
+++ running this Java
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) Client VM (build 25.51-b03, mixed mode, sharing)
+++ trying to run SikuliX
+++ using: -Xms64M -Xmx512M -Dfile.encoding=UTF-8 -Dsikuli.FromCommandLine -jar D:\Programas\SikuliX\sikulix.jar -r D:\Documentos\Telefonica\GitHub\QAVDC\Sikuli\Portal_Autoservicio\Login.sikuli
D:\Documentos\Telefonica\GitHub\QAVDC\Sikuli\Data\Conf
[error] script [ D:\Documentos\Telefonica\GitHub\QAVDC\Sikuli\Portal_Autoservicio\Login.sikuli ] stopped with error in line 17
[error] SyntaxError ( !!WHILE IMPORTING!! no viable alternative at character '?' (Conf.py, line 4) )
Exception in thread "MainThread" java.lang.IllegalStateException: No match found
        at java.util.regex.Matcher.group(Unknown Source)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSourceWalkTrace(JythonScriptRunner.java:356)
        at org.sikuli.scriptrunner.JythonScriptRunner.findErrorSource(JythonScriptRunner.java:321)
        at org.sikuli.scriptrunner.JythonScriptRunner.runPython(JythonScriptRunner.java:226)
        at org.sikuli.scriptrunner.JythonScriptRunner.runScript(JythonScriptRunner.java:183)
        at org.sikuli.scriptrunner.ScriptingSupport$RunBox.run(ScriptingSupport.java:597)
        at org.sikuli.scriptrunner.ScriptingSupport$RunBox.access$400(ScriptingSupport.java:513)
        at org.sikuli.scriptrunner.ScriptingSupport.runscript(ScriptingSupport.java:442)
        at org.sikuli.ide.SikuliIDE.run(SikuliIDE.java:206)
        at org.sikuli.ide.Sikulix.main(Sikulix.java:21)
```

**Comment by RaiMan** [comment]
imported .py files containing utf-8 characters must have 

# -*- coding: utf-8 -*- 

as first line.
For a SikuliX main script (the one that is run) this is done automatically.

**Comment by pganuza** [comment]
Thanks! That seems to work.
