### ISSUE TITLE
Sikulix IDE crashes on when Quit

### ISSUE THREAD

**Issue by sergey-plevako-badoo** [RaiMan/SikuliX-2014#158]
**OS:** Mac OS X 10.10.3 (14D136)
**Java:** Java 7 (x86_64) 1.7.0_71-b14
**SikuliX:** 2015-07-24_01:00nightly
I have chosen "Pack - 1", "Ruby (JRuby)" and "3 - Use Tesseract" during the installation.
When I press Quit from the Main Menu the SikuliX IDE crashes: 
```java
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
 at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:484)
 at org.sikuli.ide.SikuliIDE$FileAction.doQuit(SikuliIDE.java:990)
 at org.sikuli.ide.SikuliIDE.quit(SikuliIDE.java:1242)
 at org.sikuli.ide.SikuliIDE.invoke(SikuliIDE.java:445)
 at com.sun.proxy.$Proxy0.handleQuitRequestWith(Unknown Source)
 at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:387)
 at com.apple.eawt._AppEventHandler$_QuitDispatcher.performUsing(_AppEventHandler.java:380)
 at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
 at java.awt.EventQueue.access$400(EventQueue.java:82)
 at java.awt.EventQueue$2.run(EventQueue.java:676)
 at java.awt.EventQueue$2.run(EventQueue.java:674)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.Acces

sControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.IllegalThreadStateException: Cannot call method from the event dispatcher thread
 at java.awt.Robot.checkNotDispatchThread(Robot.java:465)
 at java.awt.Robot.waitForIdle(Robot.java:444)
 at org.sikuli.script.Mouse.move(Mouse.java:344)
 at org.sikuli.script.Mouse.move(Mouse.java:317)
 at org.sikuli.script.Mouse.init(Mouse.java:58)
 at org.sikuli.script.Screen.initScreens(Screen.java:89)
 at org.sikul

i.script.Screen.<clinit>(Screen.java:58)
 ... 22 more
```

**Comment by RaiMan** [comment]
do you have more than one monitor attached?

**Comment by sergey-plevako-badoo** [comment]
Yes, I do. I have external display connected to my laptop.

**Comment by RaiMan** [comment]
ok, thanks. I have to check that.
