### ISSUE TITLE
Some java.version give an exception

### ISSUE THREAD

**Issue by wernight** [RaiMan/SikuliX-2014#182]
````
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.sikuli.basics.Debug.log(Debug.java:697)
        at org.sikuli.basics.Debug.logx(Debug.java:675)
        at org.sikuli.script.RunTime.log(RunTime.java:99)
        at org.sikuli.script.RunTime.get(RunTime.java:184)
        at org.sikuli.setup.RunSetup.main(RunSetup.java:165)
Caused by: java.lang.NumberFormatException: For input string: "i"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:679)
        at java.lang.Integer.parseInt(Integer.java:797)
        at org.sikuli.basics.Settings.<clinit>(Settings.java:123)
        ... 5 more
````

From [Settings.java](https://github.com/RaiMan/SikuliX-2014/blob/2633770651102b4772f7f0276b641795c17ebd23/API/src/main/java/org/sikuli/basics/Settings.java#L123) it should have a try-catch and/or handle more cases. My `java.version` is `9-internal` hence it'd try to `Integer.parseInt("i")` which fails of course.

**Comment by RaiMan** [comment]
Thanks.
... coming right back from the future ;-)
