### ISSUE TITLE
error with 20160519.231239-26

### ISSUE THREAD

**Issue by gshields** [RaiMan/SikuliX-2014#205]
$ java -jar sikulixsetup-1.1.1-20160519.231239-26-forsetup.jar 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.sikuli.script.Sikulix.<clinit>(Sikulix.java:63)
	at org.sikuli.script.RunTime.runcmd(RunTime.java:2659)
	at org.sikuli.script.RunTime.runcmd(RunTime.java:2594)
	at org.sikuli.script.RunTime.get(RunTime.java:211)
	at org.sikuli.setup.RunSetup.main(RunSetup.java:165)
Caused by: java.lang.NullPointerException
	at org.sikuli.script.RunTime.makeFolders(RunTime.java:773)
	at org.sikuli.script.RunTime.libsExport(RunTime.java:878)
	at org.sikuli.script.RunTime.libsLoad(RunTime.java:813)
	at org.sikuli.script.RunTime.loadLibrary(RunTime.java:980)
	at org.sikuli.script.Screen.<clinit>(Screen.java:73)
	... 5 more

**Comment by gshields** [comment]
java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
on unbuntu 10.04, previous version of sikulix worked, this was a clean install

**Comment by RaiMan** [comment]
please try again, made some fixes.

**Comment by gshields** [comment]
Raimund,

Beautiful it works for jython and jruby options.

One minor thing if I choose only Jruby and then try to use the IDE, it get
...............................
[info] IDE startup: 1.8 seconds

Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:478)
at org.sikuli.ide.SikuliIDE$FileAction.doQuit(SikuliIDE.java:1059)
at org.sikuli.ide.SikuliIDE.quit(SikuliIDE.java:1311)
at org.sikuli.ide.SikuliIDE$8.windowClosing(SikuliIDE.java:2765)
at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
at java.awt.Window.processWindowEvent(Window.java:2058)
at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
at java.awt.Window.processEvent(Window.java:2017)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)

at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.aw

t.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalThreadStateException: Cannot call method from
the event dispatcher thread
at java.awt.Robot.checkNotDispatchThread(Robot.java:573)
at java.awt.Robot.waitForIdle(Robot.java:552)
at org.sikuli.script.Mouse.move(Mouse.java:352)
at org.sikuli.script.Mouse.move(Mouse.java:325)
at org.sikuli.script.Mouse.init(Mouse.java:59)
at org.sikuli.script.Screen.initScreens(Screen.java:109)
at org.sikuli.script.Screen.<clinit>(Screen.java:74)
... 30 more
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError:
Could not initialize class org.sikuli.script.Screen
at org.sikuli.script.Sikulix.cleanUp(Sikulix.java:478)
at org.sikuli.ide.SikuliIDE$FileAction.doQuit(SikuliIDE.java:1059)
at org.sikuli.ide.SikuliIDE.quit(SikuliIDE.java:1311)
at org.sikuli.ide.SikuliIDE$8.windowClosing(SikuliIDE.java:2765)
at java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:349)
at java.awt.Window.processWindowEvent(Window.

java:2058)
at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
at java.awt.Window.processEvent(Window.java:2017)
at java.awt.Component.dispatchEventImpl(Component.java:4891)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Window.dispatchEventImpl(Window.java:2750)
at java.awt.Component.dispatchEvent(Component.java:4713)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)


at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

................

It appears that jython is not optional and should not be unselected when
installing

Thanks for you great work,

George Shields

**Comment by RaiMan** [comment]
thanks for feedback. I will check the JRuby problem.
