### ISSUE TITLE
When i try to connect to VNC, it gives an error.

### ISSUE THREAD

**Issue by akash12317** [RaiMan/SikuliX-2014#207]
Code 
`
    public static void main(String[] args){

    Socket s = new Socket("192.168.1.17", 5900); 
    s.setSoTimeout(1000);
    s.setKeepAlive(true); 
    ConnectionController cc = new ConnectionController(s);
    cc.openConnection(0); 
    cc.setPixelFormat(0, "Truecolor", 32, 0); 
    cc.start(0);    
    Thread.sleep(2000);
    VNCScreen vnc = new VNCScreen();`

Error:

> ConnectedException in thread "main" java.lang.NullPointerException
    at edu.unh.iol.dlc.Framebuffer.resetPF(Framebuffer.java:84)
    at edu.unh.iol.dlc.VNCThread.setPixelFormat(VNCThread.java:147)
    at edu.unh.iol.dlc.ConnectionController.setPixelFormat(ConnectionController.java:117)
    at test_run_01.main(test_run_01.java:24)

**Comment by akash12317** [comment]
error occurs after the execution of "cc.openConnection(0); "
code:

> `s.setSoTimeout(1000);
s.setKeepAlive(true);
 ConnectionController cc = new ConnectionController(s);
cc.openConnection(0); `

error after execution of cc.openConnection(0) : 

> Exception in thread "main" java.lang.ExceptionInInitializerError
    at socket.main(socket.java:25)
Caused by: java.lang.NullPointerException
    at edu.unh.iol.dlc.VNCScreen.initScreens(VNCScreen.java:102)
    at edu.unh.iol.dlc.VNCScreen.<clinit>(VNCScreen.java:67)
    ... 1 more

**Comment by RaiMan** [comment]
should work now.
see: http://sikulix-2014.readthedocs.io/en/latest/screen.html#connecting-to-a-vnc-server-vncscreen
