### ISSUE TITLE
Unable to run sikuli setup

### ISSUE THREAD

**Issue by rakeshbabuseva** [RaiMan/SikuliX-2014#227]
Hi,

I am trying to setup sikuli but ended up with the following error

**[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh\Downloads
[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh
[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh\AppData\Roaming\Sikulix\SikulixStore
[debug] RunTimeINIT: global init: entering as: SETUP
Exception in thread "main" java.lang.NullPointerException
        at org.sikuli.script.RunTime.init(RunTime.java:549)
        at org.sikuli.script.RunTime.get(RunTime.java:291)
        at org.sikuli.setup.RunSetup.main(RunSetup.java:165)
[debug] RunTimeINIT: final cleanup
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.sikuli.script.RunTime$1.run(RunTime.java:497)**

**java - version** 
_java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) Client VM (build 25.102-b14, mixed mode, sharing)_

_downloaded the jar file from https://launchpad.net/sikuli/sikulix/1.1.0_

Can you please help me out to setup sikuli

**Comment by RaiMan** [comment]
use 1.1.1

**Comment by rakeshbabuseva** [comment]
[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh\Downloads
[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh
[debug] RunTimeINIT: loadOptions: check: C:\Users\Rakesh\AppData\Roaming\Sikulix\SikulixStore
[debug] RunTimeINIT: global init: entering as: SETUP
Exception in thread "main" java.lang.NullPointerException
        at org.sikuli.script.RunTime.init(RunTime.java:552)
        at org.sikuli.script.RunTime.get(RunTime.java:295)
        at org.sikuli.setup.RunSetup.main(RunSetup.java:163)
[debug] RunTimeINIT: final cleanup
[debug] RunTimeINIT: exists libs folder at: C:\Users\Rakesh\AppData\Roaming\Sikulix\SikulixLibs_201607192032
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError
        at org.sikuli.script.RunTime$1.run(RunTime.java:496)
Caused by: java.lang.NullPointerException
        at org.sikuli.script.RunTime.makeFolders(RunTime.java:790)
        at org.sikuli.script.RunTime.libsExport(RunTime.java:886)
        at org.sikuli.script.RunTime.libsLoad(RunTime.java:821)
        at org.sikuli.script.RunTime.loadLibrary(RunTime.java:989)
        at edu.unh.iol.dlc.VNCScreen.<clinit>(VNCScreen.java:67)
        ... 1 more

Downloaded from : http://nightly.sikuli.de/

**Comment by RaiMan** [comment]
looks like some mixup of versions.

You should delete the folder:
C:\Users\Rakesh\AppData\Roaming\Sikulix

and start allover new, putting the the downloaded setup jar into a folder like c:\SikuliX as recommended and run it again.

Take care, that in the environment nothing points to stuff from previous Sikuli versions.

**Comment by yhsung** [comment]
Try to run the cmd.exe with administrator permission might help.
