### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)

### ISSUE THREAD

**Issue by WallyCZ** [RaiMan/SikuliX-2014#295]
This happens when you want tu run sikulix IDE and your username has some non-ascii character:

Traceback (most recent call last):
  File "D:\projects\sikulix\sikulix.jar\Lib\site.py", line 585, in <module>
  File "D:\projects\sikulix\sikulix.jar\Lib\site.py", line 567, in main
  File "D:\projects\sikulix\sikulix.jar\Lib\site.py", line 300, in addusersitepackages
  File "D:\projects\sikulix\sikulix.jar\Lib\site.py", line 289, in getusersitepackages
  File "D:\projects\sikulix\sikulix.jar\Lib\sysconfig.py", line 416, in get_path
  File "D:\projects\sikulix\sikulix.jar\Lib\sysconfig.py", line 407, in get_paths
  File "D:\projects\sikulix\sikulix.jar\Lib\sysconfig.py", line 180, in _expand_vars
  File "D:\projects\sikulix\sikulix.jar\Lib\sysconfig.py", line 154, in _subst_vars
  File "D:\projects\sikulix\sikulix.jar\Lib\sysconfig.py", line 154, in _subst_vars
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 10: ordinal not in range(128)

Run on Windows 10
Latest nightly build version

**Comment by RaiMan** [comment]
Sorry, but you have to live with that problem or fix it yourself.
I will not touch the IDE anymore in version 1.1.x

Version 2 will have another solution.
