### ISSUE TITLE
Test Android By SikuliX，and get the result "Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat(III)J"

### ISSUE THREAD

**Issue by ganmaotong** [RaiMan/SikuliX-2014#301]
1、I want test android app by sikuliX,  and include sikulixapi.jar in the CLASSPATH of My Java project （sikulixapi-1.1.1）
2、My code like that：
`package com.stone.sikuli.test;

import org.junit.Test;
import org.opencv.core.Core;
import org.sikuli.android.ADBScreen;
import org.sikuli.basics.Debug;
import org.sikuli.script.FindFailed;
import org.sikuli.script.ImagePath;

public class AndroidTest {

	public static void main(String[] args) throws FindFailed, InterruptedException {
		ADBScreen s = new ADBScreen();
		s.wakeUp(5);
	       String imgpath = "D:\\image";
	       ImagePath.add(imgpath);
	       s.doubleClick("op.png");
	    
	}

}`

use Eclipse IDE，and run the application, return a Exception:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat(III)J
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:477)
	at org.sikuli.android.ADBDevice.captureDeviceScreenMat(ADBDevice.java:204)
	at org.sikuli.android.ADBDevice.captureDeviceScreen(ADBDevice.java:151)
	at org.sikuli.android.ADBDevice.captureScreen(ADBDevice.java:138)
	at org.sikuli.android.ADBScreen.capture(ADBScreen.java:148)
	at org.sikuli.android.ADBScreen.capture(ADBScreen.java:158)
	at org.sikuli.script.Region.doCheckLastSeenAndCreateFinder(Region.java:2976)
	at org.sikuli.script.Region.checkLastSeenAndCreateFinder(Region.java:2971)
	at org.sikuli.script.Region.doFind(Region.java:2900)
	at org.sikuli.script.Region.access$500(Region.java:29)
	at org.sikuli.script.Region$RepeatableFind.run(Region.java:3144)
	at org.sikuli.script.Region$Repeatable.repeat(Region.java:3100)
	at org.sikuli.script.Region.wait(Region.java:2733)
	at org.sikuli.script.Region.find(Region.java:2336)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3213)
	at org.sikuli.script.Region.doubleClick(Region.java:3745)
	at org.sikuli.script.Region.doubleClick(Region.java:3730)
	at com.stone.sikuli.test.AndroidTest.main(AndroidTest.java:20)`

how to fix the bug?

**Comment by RaiMan** [comment]
What system?

Please try latest 1.1.2 nightly.

**Comment by terces** [comment]
https://github.com/RaiMan/SikuliX-2014/issues/210#issuecomment-233162185
Try this suggestion, it works for me
