### ISSUE TITLE
Not working with multiple monitors

### ISSUE THREAD

**Issue by CoLdAs1cE** [RaiMan/SikuliX-2014#303]
i have 2 monitors, it only works on the first but i can capture images  the second screen.

```
[error] script [ what] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last): File "C:\Users\COLDAS~1\AppData\Local\Temp\Sikulix_2373568\sikuli-4333084404429505800.py", line 1, in <module> hover("1517021917872.png") Line 2782, in file Region.java 
at org.sikuli.script.Region.wait(Region.java:2782)
at org.sikuli.script.Region.find(Region.java:2329)
at org.sikuli.script.Region.getLocationFromTarget(Region.java:3238)
at org.sikuli.script.Region.mouseMove(Region.java:4032)
at org.sikuli.script.Region.hover(Region.java:3693)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
org.sikuli.script.FindFailed: FindFailed: 1517021917872.png: (189x53) in S(0)[0,0 1920x1080] E:Y, T:3.0 Line 2782, in file Region.java 
```

**Comment by RaiMan** [comment]
please ask such usage questions on launchpad.
