### ISSUE TITLE
[Exception] IDE get Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException when insert imsge

### ISSUE THREAD

**Issue by karlinmilk** [RaiMan/SikuliX-2014#308]
I can't insert any image in IDE, it always get exception as below:
[info] load image: D:/Jolin/Powershell/Pattern/ROG_GamingCenter/GamingCenter.png

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at org.sikuli.ide.EditorPatternButton.createThumbnailImage(EditorPatternButton.java:234)
at org.sikuli.ide.EditorPatternButton.setFilename(EditorPatternButton.java:204)
at org.sikuli.ide.EditorPatternButton.init(EditorPatternButton.java:76)
at org.sikuli.ide.EditorPatternButton.<init>(EditorPatternButton.java:49)
at org.sikuli.ide.SikuliIDE$ButtonInsertImage.actionPerformed(SikuliIDE.java:2180)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java

.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.secur

ity.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

And the IDE will be closed automatically if I screenshot a image.
Please help to clarify the issue.

Issue Screenshot:
https://drive.google.com/open?id=1zv9hBpnz7Mpxz5JTsaRd-FltPLXa9W_R

Sikulix- v1.1.1.1
Java - version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by RaiMan** [comment]
Are you using the shortcuts in the lefthand bar?

if yes, 
 - try with an empty tab
 - write click()
 - position the cursor between ()
 - click the "Take Screenshot" button in the top bar

What Windows is it?

**Comment by karlinmilk** [comment]
Yes, I used shorts in the lefthand bar.
I have tried the method you provided, but the issue still happened.

My windows is
Windows10 Pro
version:1709
OS build: 16299.248

Thanks
