### ISSUE TITLE
SikuliX 1.1 beta2 freezes on Click()

### ISSUE THREAD

**Issue by mucek4** [RaiMan/SikuliX-2014#45]
SikuliX freezes on Click otfen. We use 16 virtual machines (W7 32bit) for test automation and in one test (30 minutes) 2 in average freezes. 

Script always freezes in Click function. Click is written to the log and then Sikuli hangs.

Any info on that?

Thread dump shows:

    java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x15a939e8> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.lang.Object.wait(Object.java:503)
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        - locked <0x15a939e8> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.EventQueue.invokeAndWait(Unknown Source)
        at java.awt.Robot.waitForIdle(Unknown Source)
        - locked <0x1f3ab6a8> (a java.awt.Robot)
        at org.sikuli.script.RobotDesktop.mouseDown(RobotDesktop.java:97)
        at org.sikuli.script.Mouse.click(Mouse.java:436)
        at org.sikuli.script.Region.click(Region.java:3014)
        at org.sikuli.script.Region.click(Region.java:2998)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     … more from JythonScriptRunner

**Comment by RaiMan** [comment]
no more feedback
