### ISSUE TITLE
Provider org.sikuli.idesupport.JythonIDESupport not found

### ISSUE THREAD

**Issue by vantonio** [RaiMan/SikuliX-2014#51]
Sikuli 1.10-beta4 on Windows 32 bit, followed the guide results in :

Exception in thread "main" java.util.ServiceConfigurationError: org.sikuli.basic
s.IDESupport: Provider org.sikuli.idesupport.JythonIDESupport not found
        at java.util.ServiceLoader.fail(Unknown Source)
        at java.util.ServiceLoader.access$300(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
        at java.util.ServiceLoader$1.next(Unknown Source)
        at org.sikuli.basics.Settings.initScriptingSupport(Settings.java:286)
        at org.sikuli.ide.SikuliIDE.main(SikuliIDE.java:180)

Installation log:

```
[debug (14-7-28 5:17:30)] FileManager: Downloading 1.1.0-Beta4-1.jar having 3756 KB
[debug (14-7-28 5:17:44)] FileManager: downloaded 3756 KB to C:\p\11\Downloads\1.1.0-Beta4-1.jar
[debug (14-7-28 5:17:44)] FileManager: download time: 13
[debug (14-7-28 5:17:47)] RunSetup: main: Copied from Downloads: 1.1.0-Beta4-1.jar
[debug (14-7-28 5:17:48)] FileManager: Downloading 1.1.0-Beta4-4.jar having 23224 KB
[debug (14-7-28 5:18:33)] FileManager: downloaded 23224 KB to C:\p\11\Downloads\1.1.0-Beta4-4.jar
[debug (14-7-28 5:18:33)] FileManager: download time: 45
[debug (14-7-28 5:18:36)] RunSetup: main: Copied from Downloads: 1.1.0-Beta4-4.jar
[debug (14-7-28 5:18:36)] RunSetup: Download ended
[debug (14-7-28 5:18:36)] RunSetup: Downloads for selected options:
1.1.0-Beta4-1.jar - 1.1.0-Beta4-4.jar - 
[debug (14-7-28 5:18:36)] RunSetup: Download page: http://nightly.sikuli.de/
[debug (14-7-28 5:18:36)] RunSetup: recreating IDE (exclude scripting support)
[debug (14-7-28 5:18:36)] FileManager: buildJar: C:\p\11\sikuli-temp.jar
[debug (14-7-28 5:18:36)] FileManager: buildJar: adding: C:\p\11\sikulix.jar
[debug (14-7-28 5:18:39)] FileManager: buildJar: completed
[debug (14-7-28 5:18:39)] RunSetup: adding needed stuff to sikulix.jar
[debug (14-7-28 5:18:39)] FileManager: buildJar: C:\p\11\sikuli-temp.jar
[debug (14-7-28 5:18:39)] FileManager: buildJar: adding: C:\p\11\sikulix.jar
[debug (14-7-28 5:18:41)] FileManager: buildJar: adding: C:\p\11\sikulixsetup-1.1.0-Beta4.jar
[debug (14-7-28 5:18:46)] FileManager: buildJar: adding: C:\p\11\sikulijython.jar
[debug (14-7-28 5:19:06)] FileManager: buildJar: completed
[debug (14-7-28 5:19:06)] RunSetup: exporting commandfiles
[debug (14-7-28 5:19:06)] ResourceLoader: export: Trying to access package for exporting: Commands/windows#runsikulix.cmd
to: C:/p/11/
[debug (14-7-28 5:19:06)] ResourceLoader: export: from: file:/C:/p/11/sikulixsetup-1.1.0-Beta4.jar
[debug (14-7-28 5:19:07)] ResourceLoader: export: Found 1 Files in Commands/windows/runsikulix.cmd
[debug (14-7-28 5:19:09)] RunSetup: trying to set up the environment
[debug (14-7-28 5:19:09)] ResourceLoader: check: we are running on arch: x86
[debug (14-7-28 5:19:09)] ResourceLoader: check: using Java at: C:/Program Files/Java/jre7/
[error (14-7-28 5:19:09)] ResourceLoader: check: No valid libs path available until now!
[action (14-7-28 5:19:09)] ResourceLoader: check: Please wait! Trying to extract libs to jar parent folder: C:/p/11/
[debug (14-7-28 5:19:09)] ResourceLoader: extractLibs: from: file:/C:/p/11/sikulixsetup-1.1.0-Beta4.jar
[debug (14-7-28 5:19:10)] ResourceLoader: extractLibs: Found 17 Files in META-INF/libs/windows/libs32/
[debug (14-7-28 5:19:11)] ResourceLoader: checkLibsDir: trying: C:\p\11\libs
[error (14-7-28 5:19:11)] ResourceLoader: loadLib: Fatal Error 110: loading: VisionProxy.dll
[error (14-7-28 5:19:11)] ResourceLoader: loadLib: Since native library was found at C:\p\11\libs
 it might be a problem with needed dependent libraries
ERROR: C:\p\11\libs\VisionProxy.dll: Can't find dependent libraries
[error (14-7-28 5:19:11)] ResourceLoader: loadLib: Check, wether a valid Sikuli libs folder is in system path at runtime!
[error (14-7-28 5:19:11)] ResourceLoader: loadLib: Running Setup: ignoring this error for now
[debug (14-7-28 5:19:11)] ResourceLoader: checkLibsDir: Using libs at: C:\p\11\libs
[debug (14-7-28 5:19:15)] RunSetup: Trying to run functional test: running script statements via SikuliScript
[debug (14-7-28 5:19:15)] SikuliX: add to classpath: C:\p\11\sikulix.jar
[debug (14-7-28 5:19:15)] RunSetup: trying to run a test using SikuliScript with Jython
```
It strangely stopped at "RunSetup: trying to run a test using SikuliScript with Jython".

Any thoughts please?

**Comment by RaiMan** [comment]
is surely solved
